name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - name: Install and Build # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm run build:prod
        env:
          CI: true

      - name: Deploy to GitHub Pages
        # You may pin to the exact commit or the version.
        # uses: crazy-max/ghaction-github-pages@b8f8d291c97fe0edd9fb4ee73018163593418e8f
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          # Git branch where assets will be deployed
          target_branch: gh-pages # optional, default is gh-pages
          # Build directory to deploy
          build_dir: dist
          # Write the given domain name to the CNAME file
          fqdn: clintondannolfo.com # optional
          # Allow Jekyll to build your site
          jekyll: false # optional, default is true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
